import Header from '@/components/Header'
import Main from '@/components/Main'
import Wrapper from '@/components/Wrapper'
import type { Metadata } from 'next'
import { Raleway, Source_Serif_4 } from 'next/font/google'
import './globals.css'

const source_serif_4 = Source_Serif_4({ subsets: ['latin'], weight: ['200', '300', '400', '500'] })
const raleway = Raleway({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600']
})

export const metadata: Metadata = {
	title: 'Turquoise Build',
	description: 'Generated by Next.js'
}

export function generateStaticParams() {
	return [{ lang: 'en' }]
}

export default function RootLayout({
	children,
	params
}: {
	children: React.ReactNode
	params: any
}) {
	return (
		<html lang={params.lang}>
			<body className={raleway.className}>
				<Wrapper>
					<Header lang={params.lang} />
					<Main>{children}</Main>
				</Wrapper>
			</body>
		</html>
	)
}
