import Header from '@/components/Header'
import Main from '@/components/Main'
import type { Metadata } from 'next'
import { Source_Serif_4 } from 'next/font/google'
import './globals.css'

const source_serif_4 = Source_Serif_4({ subsets: ['latin'], weight: ['200', '300', '400', '500'] })

export const metadata: Metadata = {
	title: 'Turquoise Build',
	description: 'Generated by Next.js'
}

export function generateStaticParams() {
	return [{ lang: 'en' }]
}

export default function RootLayout({
	children,
	params
}: {
	children: React.ReactNode
	params: any
}) {
	return (
		<html lang={params.lang}>
			<body className={source_serif_4.className}>
				<Main>
					<Header />
					<main className="mt-headerHeight  mx-auto max-w-screen-lg">{children}</main>
				</Main>
			</body>
		</html>
	)
}
